/** Shared test fixtures. Not a *.test.ts file, so Vitest won't execute it as a suite. */
export const FULL_ENV = {
  DEEPSEEK_API_KEY: "ds",
  TELEGRAM_BOT_TOKEN: "t",
  TELEGRAM_ALLOWED_CHAT_ID: "1",
  TELEGRAM_WEBHOOK_SECRET: "s",
  NOTION_TOKEN: "n",
  NOTION_EVIDENCE_DB_ID: "e",
  NOTION_TODAY_PAGE_ID: "td",
  NOTION_DECKS_DB_ID: "d",
  NOTION_SYLLABUS_DB_ID: "sy",
  NOTION_LEDGER_PAGE_ID: "lg",
  NOTION_STUDYMAP_PAGE_ID: "sm",
  NOTION_DAILYLOG_PAGE_ID: "dl",
  NOTION_GRADEBOOK_PAGE_ID: "gb",
  NOTION_SCORECARD_PAGE_ID: "sc",
  NOTION_LESSONS_DB_ID: "lessons-db",
  NOTION_ACTIONQUEUE_DB_ID: "queue-db",
  NOTION_RETAINED_PAGE_ID: "retained-page",
  NOTION_ASSIGNMENTS_DB_ID: "assignments-db",
  NOTION_LISTENING_PAGE_ID: "listening-page",
  AGENT_SECRET: "agent-secret",
  CRON_SECRET: "c",
};
