/**
 * One-time / provenance: build lib/hsk/generated.ts (the committed HSK 3.0 dataset) from raw
 * word lists dropped in materials/hsk30/. Never runs on Vercel — runtime imports the committed
 * output only, so the cron path has no network dependency.
 *
 * Sources (materials/hsk30/, fetched once):
 *   th-1.txt / th-2.txt / th-3.txt  — HSK 3.0 (GF0025-2021) per-band word lists, one word/line.
 *       github.com/tonghuikang/HSK-3.0-words-list  (band sizes 500 / 771 / 973 — the official
 *       per-band counts; each word belongs to exactly one band; "HSK 3 = 973 words" = band 3).
 *   new-1.json / new-2.json / new-3.json — pinyin + gloss lookup.
 *       github.com/drkameleon/complete-hsk-vocabulary (wordlists/exclusive/new).
 *
 * Each HSK word is tagged with its LOWEST band (first appearance) so banding is exclusive and
 * the cumulative HSK-1..3 set is the union. Characters are derived from the words, each tagged
 * with the lowest band it appears in. Grammar points are hand-curated in lib/hsk/data.ts.
 *
 * Usage:  npm run build:hsk    (then commit lib/hsk/generated.ts)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const DIR = join("materials", "hsk30");
const BANDS = [1, 2, 3] as const;

// A few pinyin the drkameleon set misses (kept tiny + explicit so the gap is auditable).
const PINYIN_OVERRIDE: Record<string, { py: string; def: string }> = {
  示: { py: "shì", def: "to show; to indicate" },
  "…极了": { py: "jí le", def: "extremely (after an adjective)" },
};

function readWords(band: number): string[] {
  return readFileSync(join(DIR, `th-${band}.txt`), "utf8")
    .split(/\r?\n/)
    .map((s) => s.trim())
    .filter(Boolean);
}

function pinyinMap(): Map<string, { py: string; def: string }> {
  const m = new Map<string, { py: string; def: string }>();
  for (const b of BANDS) {
    const arr = JSON.parse(readFileSync(join(DIR, `new-${b}.json`), "utf8")) as Array<{
      simplified: string;
      forms?: Array<{ transcriptions?: { pinyin?: string }; meanings?: string[] }>;
    }>;
    for (const e of arr) {
      const f = e.forms?.[0];
      const py = f?.transcriptions?.pinyin;
      if (e.simplified && py && !m.has(e.simplified)) {
        m.set(e.simplified, { py, def: f?.meanings?.[0] ?? "" });
      }
    }
  }
  for (const [w, v] of Object.entries(PINYIN_OVERRIDE)) if (!m.has(w)) m.set(w, v);
  return m;
}

const isHanzi = (ch: string) => /[一-鿿]/.test(ch);

function main() {
  const py = pinyinMap();

  // Word → lowest band (exclusive tagging).
  const wordBand = new Map<string, number>();
  for (const b of BANDS) for (const w of readWords(b)) if (!wordBand.has(w)) wordBand.set(w, b);

  // Character → lowest band it appears in.
  const charBand = new Map<string, number>();
  for (const [w, b] of wordBand) {
    for (const ch of w) {
      if (!isHanzi(ch)) continue;
      const prev = charBand.get(ch);
      if (prev === undefined || b < prev) charBand.set(ch, b);
    }
  }

  const words = [...wordBand.entries()].sort((a, b) => a[1] - b[1]);
  const chars = [...charBand.entries()].sort((a, b) => a[1] - b[1]);

  const perBand = (m: Map<string, number>) =>
    BANDS.map((b) => [...m.values()].filter((x) => x === b).length);

  // Packed as newline-delimited "word|pinyin|band" rows and parsed once at load. Avoids a 2000+
  // element typed literal (TypeScript TS2590 "union too complex") and keeps the file compact.
  // Chinese headwords and pinyin never contain "|" or newlines, so the delimiter is safe.
  const wordRows = words.map(([w, b]) => `${w}|${py.get(w)?.py ?? ""}|${b}`).join("\n");
  const charRows = chars.map(([c, b]) => `${c}|${b}`).join("\n");

  const out = `// GENERATED by scripts/build-hsk-data.ts — do not edit by hand.
// HSK 3.0 (GF0025-2021) bands 1-3. Sources: tonghuikang/HSK-3.0-words-list (bands),
// drkameleon/complete-hsk-vocabulary (pinyin). Regenerate with: npm run build:hsk
// Band word counts: ${perBand(wordBand).join(" / ")} (per-band, exclusive) — union ${words.length}.
// Character counts: ${perBand(charBand).join(" / ")} — union ${chars.length}.
import type { HskWord, HskChar, HskBand } from "./data";

// Packed "word|pinyin|band" rows (parsed once below) to stay compact and dodge TS2590.
const WORD_ROWS = ${JSON.stringify(wordRows)};
const CHAR_ROWS = ${JSON.stringify(charRows)};

export const HSK_WORDS: HskWord[] = WORD_ROWS.split("\\n").map((r) => {
  const [w, py, band] = r.split("|");
  return { w, py, band: Number(band) as HskBand };
});

export const HSK_CHARS: HskChar[] = CHAR_ROWS.split("\\n").map((r) => {
  const [c, band] = r.split("|");
  return { c, band: Number(band) as HskBand };
});
`;

  writeFileSync(join("lib", "hsk", "generated.ts"), out, "utf8");
  console.log(
    `Wrote lib/hsk/generated.ts — ${words.length} words (bands ${perBand(wordBand).join("/")}), ` +
      `${chars.length} chars.`
  );
}

main();
